### PR TITLE
coerce env string to directory

### LINKED ISSUE #11: Incorrect config-directory output with XDG_CONFIG_HOME env var
Currently, function `config-directory` outputs this on my system:
```cl
CL-USER> (ubiquitous:config-directory)
#P"/home/semi/common-lisp/ubiquitous/.config"
```
I believe this is because environment variables for directories don't have forward slashes at the end, causing `merge-pathnames` to coerce the string to a file instead of a directory.

### PR DESCRIPTION
**Pull request by semilin**
Fixes #11

### CODE REVIEW

**Comment by Shinmera** [comment]
This is unfortunately not a correct fix. Specifically, make-pathname specifies:
> If the directory is a [string](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_s.htm#string), it should be the name of a top level directory, and should not contain any punctuation characters; that is, specifying a [string](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_s.htm#string), str, is equivalent to specifying the list (:absolute str).

If it works, it only does so accidentally on your implementation.

**Comment by semilin** [comment]
Ah, good catch. I can't seem to find any built-in function that can ensure that a string is converted into a directory, weirdly. I've found that `force-directory` from your pathname-utils library works, at least for me, but I'd guess you probably don't want to bring that in as a dependency. I could try to extract the necessary functions if you think that's the best approach.

**Comment by Shinmera** [comment]
Well, even force-directory won't be good, since it'll parse a namestring first, which is problematic in the first place due to the way namestrings can contain special characters, which a native namestring wouldn't care about. Eg: `/home/[foo]/` will not parse as expected.

I think the right thing to do is to copy the `parse-native-namestring` functions from pathname-utils out and use them with the `:type :directory` flag. Maybe sans the environment variable parsing parts, though.

**Comment by semilin** [comment]
Sorry I got to this late. 
> Maybe sans the environment variable parsing parts, though.

Could you elaborate what you meant by this?

**Comment by Shinmera** [comment]
parse-native-namestring calls parse-dos-namestring on Windows platforms, which relies on getenv in the presence of environment variables in the namestring.

**Comment by semilin** [comment]
This is obviously a pretty hacky way of removing the getenv parsing from the Windows version - is it worth adding an error condition instead?

**Comment by Shinmera** [comment]
Nah, I think this is fine.

**Comment by Shinmera** [comment]
Though I would actually also pass `:junk-allowed T` when parsing it for the config directory.

**Comment by Shinmera** [comment]
Thanks for all the work!

**Comment by semilin** [comment]
Thanks for the help!

**Pull request merged**
